spring:
  application:
    name: InSpectrum

  datasource:
    url: jdbc:postgresql://localhost:5432/neuro_app
    username: neuro
    password: neuro_password

#  jackson:
#    property-naming-strategy: SNAKE_CASE



