spring:
  application:
    name: InSpectrum

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:127.0.0.1}:${DATABASE_PORT:5432}/${DATABASE_NAME:neuro_app}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml


  jackson:
   property-naming-strategy: SNAKE_CASE

jwt:
  secret: ${JWT_SECRET:a-string-secret-at-least-256-bits-long}
  ttl-millis: ${JWT_TTL:604800000} # 1 week in millisecond